version: '3.8'

services:
  app:
    container_name: e-commerce
    build:
      context: .
      dockerfile: Dockerfile
    command: 'nest start --watch'
    volumes:
      - .:/app
    ports:
      - '3333:3333' 
    environment:
      DATABASE_URL: ${DATABASE_URL}

volumes:
  dbdata: